"""Read-only capability catalog for the future GACE App and AI adapter."""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any


READ_ONLY_CAPABILITIES: tuple[dict[str, Any], ...] = (
    {
        "id": "system.health.read",
        "method": "GET",
        "path": "/health",
        "scope": "system:read",
        "description": "读取服务版本、认证状态和执行模式。",
        "requires_auth": False,
    },
    {
        "id": "runtime.plan.read",
        "method": "GET",
        "path": "/api/v1/runtime/plan",
        "scope": "runtime:read",
        "description": "读取数据、研究、模拟盘和风险门禁的统一运行状态。",
        "requires_auth": True,
    },
    {
        "id": "market.overview.read",
        "method": "GET",
        "path": "/api/v1/market/overview",
        "scope": "market:read",
        "description": "读取交易所连接和行情状态。",
        "requires_auth": True,
    },
    {
        "id": "market.summary.read",
        "method": "GET",
        "path": "/api/v1/market/summary",
        "scope": "market:read",
        "description": "读取已校验 K 线驱动的市场摘要。",
        "requires_auth": True,
    },
    {
        "id": "market.compare.read",
        "method": "GET",
        "path": "/api/v1/market/compare",
        "scope": "market:read",
        "description": "读取跨市场收盘价差研究结果。",
        "requires_auth": True,
    },
    {
        "id": "market.opportunities.history.read",
        "method": "GET",
        "path": "/api/v1/market/opportunities/history",
        "scope": "market:read",
        "description": "读取已持久化的 L2 机会扫描证据；不包含交易授权。",
        "requires_auth": True,
    },
    {
        "id": "news.summary.read",
        "method": "GET",
        "path": "/api/v1/news/summary",
        "scope": "news:read",
        "description": "读取带来源新闻事件的摘要和接入状态。",
        "requires_auth": True,
    },
    {
        "id": "news.events.read",
        "method": "GET",
        "path": "/api/v1/news/events",
        "scope": "news:read",
        "description": "读取带来源、时间和风险标签的新闻事件。",
        "requires_auth": True,
    },
    {
        "id": "news.resonance.read",
        "method": "GET",
        "path": "/api/v1/news/resonance",
        "scope": "news:read",
        "description": "读取新闻事件与已校验行情的研究共振候选。",
        "requires_auth": True,
    },
    {
        "id": "tradeplan.summary.read",
        "method": "GET",
        "path": "/api/v1/tradeplan/summary",
        "scope": "runtime:read",
        "description": "读取 24/7 交易计划和当前安全状态。",
        "requires_auth": True,
    },
    {
        "id": "system.readiness.read",
        "method": "GET",
        "path": "/api/v1/system/readiness",
        "scope": "system:read",
        "description": "读取服务、历史数据和研究就绪度。",
        "requires_auth": True,
    },
    {
        "id": "history.coverage.read",
        "method": "GET",
        "path": "/api/v1/history/coverage",
        "scope": "history:read",
        "description": "读取历史数据集覆盖率和质量门禁状态。",
        "requires_auth": True,
    },
    {
        "id": "history.candles.read",
        "method": "GET",
        "path": "/api/v1/history/candles",
        "scope": "history:read",
        "description": "读取指定交易所和交易对的已校验 K 线。",
        "requires_auth": True,
    },
    {
        "id": "advice.summary.read",
        "method": "GET",
        "path": "/api/v1/advice/summary",
        "scope": "advice:read",
        "description": "读取研究候选摘要和数据门禁。",
        "requires_auth": True,
    },
    {
        "id": "advice.candidates.read",
        "method": "GET",
        "path": "/api/v1/advice/candidates",
        "scope": "advice:read",
        "description": "读取跨市场研究候选，不包含真实交易授权。",
        "requires_auth": True,
    },
    {
        "id": "strategy.incubators.read",
        "method": "GET",
        "path": "/api/v1/incubators",
        "scope": "strategy:read",
        "description": "读取筛选结果沉淀的策略候选孵化池及阶段状态。",
        "requires_auth": True,
    },
    {
        "id": "strategies.catalog.read",
        "method": "GET",
        "path": "/api/v1/strategies/catalog",
        "scope": "strategy:read",
        "description": "读取策略目录、参数合同和可用运行模式。",
        "requires_auth": True,
    },
    {
        "id": "strategies.packages.read",
        "method": "GET",
        "path": "/api/v1/strategies/packages",
        "scope": "strategy:read",
        "description": "读取内置和已登记策略包的版本元数据；自定义包不会直接执行。",
        "requires_auth": True,
    },
    {
        "id": "strategies.matrices.read",
        "method": "GET",
        "path": "/api/v1/strategies/matrices",
        "scope": "strategy:read",
        "description": "读取策略与已校验历史数据集的矩阵研究记录。",
        "requires_auth": True,
    },
    {
        "id": "research.runs.read",
        "method": "GET",
        "path": "/api/v1/research/runs",
        "scope": "research:read",
        "description": "读取研究、策略比较和参数搜索归档。",
        "requires_auth": True,
    },
    {
        "id": "backtests.runs.read",
        "method": "GET",
        "path": "/api/v1/backtests/runs",
        "scope": "backtest:read",
        "description": "读取回测结果和可复现参数。",
        "requires_auth": True,
    },
    {
        "id": "paper.summary.read",
        "method": "GET",
        "path": "/api/v1/paper/summary",
        "scope": "paper:read",
        "description": "读取模拟账户、仓位和模拟订单摘要。",
        "requires_auth": True,
    },
    {
        "id": "risk.summary.read",
        "method": "GET",
        "path": "/api/v1/risk/summary",
        "scope": "risk:read",
        "description": "读取风险政策、阻断原因和安全暂停状态。",
        "requires_auth": True,
    },
    {
        "id": "notifications.summary.read",
        "method": "GET",
        "path": "/api/v1/notifications/summary",
        "scope": "notifications:read",
        "description": "读取独立站内通知摘要。",
        "requires_auth": True,
    },
    {
        "id": "assistant.actions.read",
        "method": "GET",
        "path": "/api/v1/assistant/actions",
        "scope": "assistant:read",
        "description": "读取 GACE AI 可发现的只读 Action 清单。",
        "requires_auth": True,
    },
    {
        "id": "tasks.read",
        "method": "GET",
        "path": "/api/v1/tasks",
        "scope": "tasks:read",
        "description": "读取历史下载、研究、回测和模拟任务状态。",
        "requires_auth": True,
    },
)


def build_capability_catalog(settings: Any) -> dict[str, object]:
    """Return a stable, explicit read-only surface for future adapters."""
    return {
        "schema_version": "gace-capability-catalog-v1",
        "app_id": "com.crypto-platform.quant",
        "app_version": str(settings.version),
        "runtime": "standalone",
        "execution_mode": str(settings.execution_mode),
        "read_only": True,
        "capabilities": [dict(item, risk_level="READ_ONLY", enabled=True) for item in READ_ONLY_CAPABILITIES],
        "write_capabilities": [],
        "blocked_actions": [
            {
                "id": "execution.live_order.submit",
                "risk_level": "HIGH_RISK",
                "reason": "真实执行模式为 DISABLED，未接入真实账户和下单适配器。",
            },
            {
                "id": "execution.withdraw.submit",
                "risk_level": "HIGH_RISK",
                "reason": "系统不提供提币、资金转移或提现能力。",
            },
        ],
        "generated_at": datetime.now(UTC).isoformat(),
    }
